config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :dashboard, only: [:index]
  resources :language_users

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
    resources :entries
  end

  namespace :api do
    resources :language_users
    resources :entries, only: [:index]
  end

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  STUDY_HABITS = %w(listening reading writing speaking).freeze

  belongs_to :language
  belongs_to :user

  validates :user_id, presence: true
  validates :language_id, presence: true

  validates :study_habit, presence: true, inclusion: { in: STUDY_HABITS }

  scope :by_study, -> { group_by(&:study_habit) }
  scope :by_language, -> { includes(:language).group_by { |e| e.language.name } }
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :language_users
  has_many :users, through: :language_users

  default_scope { order(:name) }
end

app/models/language_user.rb
class LanguageUser < ApplicationRecord
  belongs_to :user
  belongs_to :language

  validates :language_id, presence: true, uniqueness: { scope: :user_id }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable, :rememberable

  has_many :language_users
  has_many :languages, through: :language_users
  has_many :entries
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ActionController::API
  end
end

app/controllers/api/entries_controller.rb
module Api
  class EntriesController < ApiController
    respond_to :json

    def index
      respond_with EntriesSerializer.new(params.reverse_merge({
        user_id: current_user.id
      }))
    end
  end
end

app/controllers/api/language_users_controller.rb
module Api
  class LanguageUsersController < ApiController

    def index
      languages = Language.joins(:language_users).where(
        "language_users.user_id": current_user.id
      )

      render json: languages
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @language_user = LanguageUser.new
    @languages = current_user.languages
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  respond_to :html

  def index
    @entries = Entry.where(user_id: current_user.id)
                    .order('id asc')
                    .last(5)
                    .map { |entry| 
                      DashboardEntryPresenter.new(entry) 
                    }
  end
  
  def new
    @form = EntryForm.new(user: current_user)
  end

  def create
    @form = EntryForm.new(create_entry_params.merge(user: current_user))
    @form.save

    respond_with(@form, location: dashboard_index_path)
  end

  def edit
    @form = EditEntryForm.new(
      user: current_user,
      entry: current_user.entries.where(id: params[:id]).first
    )
  end

  def update
    @form = EditEntryForm.new(edit_entry_params.merge(
      user: current_user,
      entry: current_user.entries.where(id: params[:id]).first
    ))

    @form.save

    respond_with(@form, location: entries_path)
  end

  def destroy
    entry = Entry.find(params[:id])
    entry.destroy

    respond_with(200, location: entries_path)
  end

  private

  def edit_entry_params
    params.require(:edit_entry_form).permit(
      :language_studied, :duration, :duration_type,
      :study_habit, :notes
    )
  end

  def create_entry_params
    params.require(:entry_form).permit(
      :language_studied, :notes, entries: [
        :duration, :duration_type, :study_habit
      ]
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/language_users_controller.rb
class LanguageUsersController < ApplicationController

  def create
    LanguageUser.create(language_association)
    redirect_to dashboard_index_path
  end

  private

  def language_association
    Array(lang_user_params[:language_id]).map do |id|
      { language_id: id, user_id: current_user.id }
    end
  end

  def lang_user_params
    params.require(:language_user).permit(language_id: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<% content_for(:partials) do %>
  <%= render 'shared/language_modal', language_user: @language_user, languages: @languages %>
  <%= javascript_include_tag 'https://www.gstatic.com/charts/loader.js' %>
<% end %>

<div class='row'>
  <div class='col header'>
    <h1>Dashboard</h1>
  </div>
</div>

<div class='row'>
  <div class='col-3'>
    <section id='sidebar'>
      <p>Currently studying: </p>

      <ul class='current-languages'>
        <% @languages.each do |lang| %>
          <li><%= lang.name %></li>
        <% end %>
      </ul>

    </section>
    <section class='actions'>
      <button type='button' data-toggle='modal' data-target='#language-form' class='btn btn-outline-secondary btn-sm add-language'>More Languages</button>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'sign-out' %>
    </section>
  </div>

  <div class='col-9'>

    <div id='dashboard-view'>
      <section>
        <div id='chart-view'>
          <div id='progress-chart'>
          </div>
          <div class='card-columns'>

            <div class='card'>
              <h5 class='card-header'>How You Study</h5>
              <div class='card-body'>
                <div id='language-chart'>
                </div>
              </div>
            </div>

            <div class='card'>
              <h5 class='card-header'>What You Study</h5>
              <div class='card-body'>
                <div id='multi-language-chart'>
                </div>
              </div>
            </div>

            <% @languages.each do |language| %>
              <div class='card'>
                <h5 class='card-header'><%= language.name %></h5>
                <div class='card-body'>
                  <div id=<%="language-#{language.id}-chart"%>>
                    <div class='no-data-filler'><p>No data has been recorded for this language. Try adding a new entry.</p></div>
                  </div>
                </div>
              </div>
            <% end %>

          </div>
        </div>
      </section>


      <footer class='actions'>
      </footer>
    </div>
  </div>
</div>

app/views/entries/_study_habit.html.erb
<section id=<%="entry-study-#{habit}-view"%> class='study_habit'>
  <div class='custom-control custom-checkbox'>
    <input id=<%="study_habit_#{habit}"%> class='custom-control-input' type='checkbox'>
    <label for=<%="study_habit_#{habit}"%> class='custom-control-label'>
      <%= habit.upcase %>
    </label>
  </div>

  <section class='habit-fields'>
    <%= fields_for 'entry_form[entries][]', @form.proxy_entry do |f| %>
      <%= f.number_field :duration, class: 'form-control' %>
      <%= f.select :duration_type, options_for_select({ "Choose time" => "", "Minutes" => "Minutes", "Hours" => "Hours" }), {}, { class: 'form-control'} %>
      <%= f.hidden_field :study_habit, class: 'form-control', value: habit %>
    <% end %>
  </section>
</section>

app/views/entries/edit.html.erb
<h1>Update Entry</h1>

<%= form_for(@form, method: :put, url: entry_path(@form.entry)) do |f| %>
  <section>
    <legend>How you studied:</legend>
    <%= f.select :study_habit, Entry::STUDY_HABITS %> 
  </section>

  <section>
    <legend>What you studied</legend>
    <%= f.select :language_studied, options_for_select(@form.language_options, @form.language_default) %>
  </section>

  <section class='habit-fields'>
    <legend>How long you studied</legend>
    <%= f.number_field :duration, class: 'form-control'  %>
    <%= f.select :duration_type, options_for_select(["Minutes", "Hours"], @form.duration_type), {}, { class: 'form-control'} %>
  </section>

  <section>
    <%= f.submit 'Update' %>
  </section>
<% end %>

<%= link_to 'Back to Dashboard', dashboard_index_path %>

app/views/entries/index.html.erb
<div class='row header'>
  <div class='col'>
    <h1>Most Recent Entries</h1>
  </div>
</div>

<div class='row'>
  <div class='col'>
    <section>
      <table class='most-recent table table-dark'>
        <thead>

          <tr>
            <td scope="col">Language</td>
            <td scope="col">Study Method</td>
            <td scope="col">Study Time</td>
          </tr>
        </thead>

        <tbody>
          <% @entries.each do |entry| %>
            <tr>
              <td><%= entry.language_name %></td>
              <td><%= entry.study_habit %></td>
              <td><%= entry.study_time %></td>
              <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
              <td><%= link_to 'Delete', entry_path(entry), method: :delete, confirm: :true %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </section>
  </div>
</div>

app/views/entries/new.html.erb
<div class='row'>
  <div class='col header'>
    <h1>New Entry</h1>
  </div>
</div>

<div class='row'>
  <div class='col'>
    <%= form_for @form, url: entries_path do |f| %>
      <fieldset class="form-group" id='language'>
        <legend>What did you study?</legend>
        <%= f.select :language_studied, @form.language_options, {}, { class: 'form-control' } %>
      </fieldset>

      <fieldset class="form-group" id='study_habits'>
        <legend>How did you study?</legend>

        <% Entry::STUDY_HABITS.each do |habit| %>
          <%= render 'study_habit', habit: habit %>
        <% end %>

      </fieldset>

      <fieldset class="form-group" id='notes'>
        <legend>Quick Notes</legend>
        <%= f.text_area :notes, class: 'form-control', rows: 3 %>
      </fieldset>

      <footer>
        <%= f.submit "Save today's effort!", class: 'btn btn-primary' %>
        <%= link_to 'Back to Dashboard', dashboard_index_path %>
      </footer>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<h1>LangGPS</h1>
<h2>Measure the progress of your language learning</h2>

<section>
  <%= link_to 'Sign In', new_user_session_path %>
  <%= link_to 'Register', new_user_registration_path %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LangGps</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <nav class="navbar fixed-top navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="/dashboard">LangGPS</a>

    <ul class='navbar-nav'>
      <li class='nav-item'>
        <%= link_to 'Entries', entries_path, class: 'nav-link'  %>
      </li>
      <li class='nav-item'>
        <%= link_to 'New Entry', new_entry_path, class: 'nav-link'  %>
      </li>
    </ul>
  </nav>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <div class='container'>
      <%= yield %>
    </div>
  </body>

  <%= yield(:partials) if content_for?(:partials) %>

  <script>
    new App.RouteTemplate().call(); 
  </script>
</html>

app/views/shared/_language_modal.html.erb
<%#
  This partial has two dependencies
    - langauge_user (a LanguageUser object)
    - languages (a collection of Language objects)

  When rendering this partial please be sure to provide these variables.
    `render 'language_modal', language_user: LanguageUser.new, languages: current_user.langauges`
%>

<div id='language-form' class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Choose your languages</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for language_user do |f| %>
        <div class="modal-body">
            <%= f.label "Languages" %>
            <%= f.collection_check_boxes :language_id, (Language.all - languages), :id, :name do |b| %>
              <fieldset><%= b.label { b.check_box + b.text } %></fieldset>
            <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit 'Finish', class: 'btn btn-primary', data: { disable_with: "Saving..." } %>
        </div>
      </div>
    <% end %>
  </div>
</div>